# Replace "your-app-name" with the actual name of your Cloudflare Worker or Pages project.
name = "your-app-name"

# Set the compatibility date to a recent date.
# This ensures your worker uses a specific version of the Workers runtime.
compatibility_date = "2025-06-07" # You can update this to the current date or a recent one.

# If your project includes a Worker script (e.g., for server-side logic),
# specify its entry point here. For many Next.js on Cloudflare setups (e.g., using @cloudflare/next-on-pages),
# this would point to a generated worker file.
# Example: main = ".vercel/output/functions/__next_launcher.func/index.js"
# main = "src/index.ts"

# The `wrangler deploy` command, as per your error log, requires an assets directory.
# The error message suggested "./dist" as an example.
# If your Next.js build process (e.g., `next build && next export -o dist`) outputs to "./dist",
# then this path is correct.
# If your static build output is in a different directory (e.g., "out/" from `next export`, or you only want to serve "public/"),
# you should change the path below.
# For a standard `next build` (App Router without export), deploying static assets this way for a full app
# might require a more complex setup or using Cloudflare Pages, which typically expects ".next".
[assets]
directory = "./dist"
# include = ["**/*"] # Optional: By default, all files in the directory are included.
# exclude = []      # Optional: Specify files or patterns to exclude.

# If you are using Cloudflare Pages and not `wrangler deploy` directly for a worker with assets,
# your wrangler.toml might look different or these settings might be in the Cloudflare dashboard.
# For example, for Pages:
# pages_build_output_dir = ".next"
# [build]
# command = "npm run build"
