
# Replace "TruthSleuth" with the actual name of your Cloudflare Worker or Pages project if different.
name = "TruthSleuth"

# Set the compatibility date to a recent date.
# This ensures your worker uses a specific version of the Workers runtime.
compatibility_date = "2025-06-07" # You can update this to the current date or a recent one.

# If your project includes a Worker script (e.g., for server-side logic),
# specify its entry point here. For many Next.js on Cloudflare setups (e.g., using @cloudflare/next-on-pages),
# this would point to a generated worker file.
# Example: main = ".vercel/output/functions/__next_launcher.func/index.js"
# main = "src/index.ts"

# The `wrangler deploy` command requires an assets directory.
# With `output: 'export'` in next.config.ts, Next.js will build static assets to the "out/" directory by default.
# Ensure your Cloudflare build command runs `npm run build` (which executes `next build`).
[assets]
directory = "./out" # Changed from "./dist" to "./out"
# include = ["**/*"] # Optional: By default, all files in the directory are included.
# exclude = []      # Optional: Specify files or patterns to exclude.

# If you are using Cloudflare Pages and not `wrangler deploy` directly for a worker with assets,
# your wrangler.toml might look different or these settings might be in the Cloudflare dashboard.
# For example, for Pages, you might use:
# pages_build_output_dir = "out"
# [build]
# command = "npm run build"
