
# Replace "TruthSleuth" with the actual name of your Cloudflare Worker or Pages project if different.
name = "TruthSleuth"

# Set the compatibility date to a recent date.
# This ensures your worker uses a specific version of the Workers runtime.
compatibility_date = "2025-06-07" # You can update this to the current date or a recent one.

# If your project includes a Worker script (e.g., for server-side logic),
# specify its entry point here. For many Next.js on Cloudflare setups (e.g., using @cloudflare/next-on-pages),
# this would point to a generated worker file.
# Example: main = ".vercel/output/functions/__next_launcher.func/index.js"
# main = "src/index.ts" # This is a placeholder, might need adjustment for Next.js server

# The assets directory configuration is typically for static assets with `wrangler deploy`.
# For a full-stack Next.js app on Cloudflare Pages, Pages handles the build output.
# If deploying as a Worker, the configuration for serving Next.js is more complex.
# [assets]
# directory = "./out" # REMOVED: No longer exporting to out/

# For Cloudflare Pages, you might define build commands and output directory in the dashboard or use a pages_build_output_dir.
# Example for Pages if configured via wrangler.toml (often done in dashboard):
# pages_build_output_dir = ".next"
# [build]
# command = "npm run build"
